Cipher
jabacat/rclc pull request #59
Opened 2022-09-28 07:23 UTC by JakeRoggenbuck

2022-09-28 18:16 UTC, adamhutchings requested changes
Typos

2022-09-28 18:16 UTC, adamhutchings commented on common/src/ciphers.rs
> +    fn caeser(&self, msg: String) -> String;
Caesar

2022-09-28 18:16 UTC, adamhutchings commented on common/src/ciphers.rs
> +    fn caeser(&self, msg: String) -> String {
Same thing

2022-09-30 21:06 UTC, adamhutchings approved these changes

2022-09-30 21:09 UTC, merged

2022-09-30 21:14 UTC, Camerooooon commented on common/src/ciphers.rs
> +    "caesar, shift".to_string()
AKA ROT-3 Right? (Just curious)

2022-09-30 21:14 UTC, Camerooooon reviewed
Looks good to me!